storage_path = "./data"
http_port = 9000
source_path = "./examples/plugin/src/client.rs"
wasm_output_dir = "./examples/output"

[upstream.http]
port = 8000

[accumulator.merkle]

[archive.file]
directory = "./archive"

[downstream.blackhole]
