[package]
name = "wasm_plugin_client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
wasm_plugin_sdk_derive = { path = "../../wasm_plugin_sdk_derive" }

[profile.release]
opt-level = "z"
lto = true

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=--max-memory=134217728"]
